### ISSUE TITLE
how to realize autoplay? is it possible?

### ISSUE THREAD

**Issue by Barklim** [richardscarrott/react-snap-carousel#17]

**Comment by richardscarrott** [comment]
I think it's a bad idea as it takes control away from the user, but you could implement it relatively easily, something like this:

```tsx
useEffect(() => {
    const timeout = setTimeout(() => {
      if (activePageIndex === pages.length - 1) {
        goTo(0)
      } else {
        goTo(activePageIndex + 1)
      }
    }, 2500);
    return () => clearTimeout(timeout);
  }, [activePageIndex, pages]);
```

You might want to disable it when a user's mouse is hovered over it, or perhaps when a user is scrolling.

https://codesandbox.io/s/react-snap-carousel-autoplay-j38xzj?file=/src/Carousel.tsx:1342-1607

**Comment by richardscarrott** [comment]
Closing as can be implemented by user as per above.
