### ISSUE TITLE
Suggestion: Add mouse click + drag support

### ISSUE THREAD

**Issue by Apestein** [richardscarrott/react-snap-carousel#19]
Hi there, really great job with this library. It's the most flexible/customizable carousel I've seen. Only one problem though, no touch/drag scroll support. I managed to get it working by combining it with [another library](https://github.com/rfmiotto/react-use-draggable-scroll) but unfortunately combining them will break the snap functionality. [Check this out](https://github.com/Apestein/nextflix/blob/main/src/components/show-carousel.tsx). This would be a gamer if we could get it working.

**Comment by richardscarrott** [comment]
Have you tried the demo on mobile? It already has drag touch support through the virtue of using native scrolling.

Try it here https://richardscarrott.github.io/react-snap-carousel/?path=/story/carousel--default

Native scroll provides the best experience across devices IMO. It works great on desktop, especially with trackpads and works well on tablets / mobile devices with native scrolling physics.

One thing you can't do is click + drag with a mouse but personally that's kinda clumsy IMO, so if the user doesn't have a decent mouse input (e.g. macbook trackpad) they can use the carousel controls w/ the arrows / pagination controls.

**Comment by Apestein** [comment]
> Have you tried the demo on mobile? It already has drag touch support through the virtue of using native scrolling.
> 
> Try it here https://richardscarrott.github.io/react-snap-carousel/?path=/story/carousel--default
> 
> Native scroll provides the best experience across devices IMO. It works great on desktop, especially with trackpads and works well on tablets / mobile devices with native scrolling physics.
> 
> One thing you can't do is click + drag with a mouse but personally that's kinda clumsy IMO, so if the user doesn't have a decent mouse input (e.g. macbook trackpad) they can use the carousel controls w/ the arrows / pagination controls.

That's true but mouse drag is just nice to have. Could be implemented in a way that would preserve native mobile scroll and only activate for desktop.

**Comment by richardscarrott** [comment]
Closing as carousel uses native browser scrolling + I don't think the UX is particularly desirable.

**Comment by smkhalsa** [comment]
I think this should be reopened. Click and drag on desktop is a very common pattern for carousels and is often the expected behavior.
