### ISSUE TITLE
Feature Request: Add `prevDisabled` and `nextDisabled`

### ISSUE THREAD

**Issue by jasongerbes** [richardscarrott/react-snap-carousel#28]
Rendering previous and next buttons current requires using the `activePageIndex` and `pages.length` to determine whether each button should be disabled. For instance:

```js
const { prev, next, activePageIndex, pages } = useSnapCarousel();

const prevDisabled = activePageIndex <= 0;
const nextDisabled = activePageIndex === pages.length - 1;
```

As a nice-to-have API improvement, `useSnapCarousel` could use `activePageIndex` and `pages.length` internally to include `prevDisabled` and `nextDisabled` properties in the `SnapCarouselResult`:

```js
const { prev, next, prevDisabled, nextDisabled } = useSnapCarousel();
```

I'd be happy to create a PR for this feature

**Comment by richardscarrott** [comment]
Hi @jasongerbes -- yeah I think that makes sense as it is a little annoying having to read that logic so often.

I think returning `hasPreviousPage` and `hasNextPage` might read better as I can imagine use cases outside of disabling the button -- I have this in a carousel of mine:

```ts
const hasPreviousPage = activePageIndex > 0;
const hasNextPage = activePageIndex < pages.length - 1;
```

Happy to accept a PR for it 👍

**Comment by jasongerbes** [comment]
Hey @richardscarrott, thanks for that. I'll get a PR up shortly.

Regarding naming, would you prefer:

1. `hasPreviousPage` and `hasNextPage` (as suggested)
2. `hasPrevPage` and `hasNextPage`
3. `hasPrev` and `hasNext`

I feel 2 or 3 would be more consistent with the naming of the `prev`/`next` functions

**Comment by richardscarrott** [comment]
Yeah, let’s go with 2 🙏

**Comment by jasongerbes** [comment]
@richardscarrott, PR #29 is ready for your review
