### ISSUE TITLE
Allow initialPages & initialActivePageIndex to be passed in as option for SSR

### ISSUE THREAD

**Issue by richardscarrott** [richardscarrott/react-snap-carousel#4]
If a carousel has a known number of pages up front, e.g. it's not responsive or has a single item per page (e.g. `<SlideShow />`), it'd be nice to be able to pass in the `initialPages` & `initialActivePageIndex` as options, so the pagination UI can be rendered server side.

Before:
```ts
const items = Array.from({ length: 5 });
const { pages, activePageIndex } = useSnapCarousel();
// During SSR `pages` is `[]` & `activePageIndex` is 0
```

After:
```ts
const items = Array.from({ length: 5 });
const { pages, activePageIndex } = useSnapCarousel({
  initialPages: items.map((_, i) => [i]),
  initialActivePageIndex: 0
});
// During SSR `pages` would be `[[0], [1], [2], [3], [4]]` & `activePageIndex` 0
```

**Comment by richardscarrott** [comment]
Released in 0.3.1

**Comment by yss14** [comment]
@richardscarrott What happend to `initialActivePageIndex `? How can I achieve that a page index different to `0` is displayed as initial page?

**Comment by richardscarrott** [comment]
@yss14 upon implementing this feature I realised `initialActivePageIndex` isn't possible because native browser scroll doesn't allow you to set the initial scroll position -- the source of truth of the active page is the DOM's scroll position, so it's always the first page.

Instead it has to be done when the client hydrates, e.g.

```ts
const {
  goTo,
  // ...
} = useSnapCarousel();

useLayoutEffect(() => {
  goTo(2, { behavior: "instant" });
  // NOTE: `goTo` isn't a stable ref so can't currently be a dep -- ideally would use `useEffectEvent`.
}, []);

// ...
```

This is generally fine if you either a) don't SSR or b) the carousel is below the fold, however if this isn't the case you could avoid the CLS by setting opacity: 0 and animating it in when the client hydrates.
